### ISSUE TITLE
Can I use the "Load Box" feature via LiveHeX

### ISSUE THREAD

**Issue by gordonwong319** [architdate/PKHeX-Plugins#206] opened 2023-07-27 11:39 UTC
I'm not sure if this is a bug or not but this is what happen.
I try to load a box using the load box function under tools>data but after all the dialog box and the pokemon show up in the box preview in PKHeX, when I check in game the pokemon isn't there. So I try switching box in PKHeX, and when I switch back to that box the pokemon disappear. I then check if I set a pokemon as usual will it do the same thing, and it work fine. 
I use LiveHeX instead of editing the save directly, so I wonder if LiveHex doesn't support this function just yet. Does anyone know?

**Comment by kwsch** [comment] 2023-07-27 12:18
Livehex reads boxes when you switch, and writes individual slots when you set individual slots.

Importing a collection in one action does not trigger a write, so you'll have to manually press the write box button.

**Comment by architdate** [comment] 2023-07-27 16:24
As kurt said above, the whole box is loaded when you switch boxes around (make sure the corresponding checkbox is checked). LoadBox is to be used when you are not auto loading boxes on box switch events!

Closing this issue since its not a bug :)

**Closed by architdate** 2023-07-27 16:24 UTC

**Comment by gordonwong319** [comment] 2023-07-27 20:23
> Livehex reads boxes when you switch, and writes individual slots when you set individual slots.
> 
> Importing a collection in one action does not trigger a write, so you'll have to manually press the write box button.

Ahh,  so I just have to click the "write current box" button right after that and I will be fine. Thanks a lot for answering my question.
