### ISSUE TITLE
trainer folder broke sometime in the past 18 months

### ISSUE THREAD

**Issue by intriguedperson** [architdate/PKHeX-Plugins#141] opened 2022-03-31 03:40 UTC
I haven't used pkhex for a while, but when I try to import pokemon, it doesn't pull the information from the trainer folder. I remember it was working perfectly when crown tundra launched. (insane that it was over 1.5 years ago). I tried rerunning ALM setup, I've tried deleting the entire trainer folder and only putting pk8s. usetrainerdata is true in settings and trainers folder is in the same folder as pkhex.exe. I'm not sure what's wrong. 

Any ideas of what I can try next would be appreciated, let me know if it would be helpful to upload the trainer folder. Thanks

**Comment by Lusamine** [comment] 2022-03-31 03:51
The trainer folder has not been broken for 18 months.  You've described a probably incorrect setup for your trainer data: "only putting pk8's" which I assume means only Pokemon from gen 8.

Likely the issue is you don't have a Pokemon for every single possible game where a Pokemon might be generated from.  If you're generating in Sword and don't have data for Emerald, and mod needs it to be from Emerald, then you won't see trainer data on that Pokemon.  

You can review the wiki for custom trainer data to see the correct setup.

**Comment by intriguedperson** [comment] 2022-04-01 02:42
Yeah it's still not working. How would I go about fully clearing data from pkhex/alm. I've tried uninstalling and reinstalling but alm remembers my enabled settings, so it's not giving me a clean slate. Thanks

Heres a video of it not working if interested https://youtu.be/OeLIhUrxjUs

**Comment by Lusamine** [comment] 2022-04-01 02:45
Delete everything, reinstall, and only copy `trainers` in.

**Comment by intriguedperson** [comment] 2022-04-01 02:54
Yeah that's what I'm referring to by uninstalling. Deleted entire folder with plugins, pkhex, cfg. Reinstalled using almsetup but it still remembers my alm settings so something isn't being cleared. I've tried emptying recycle bin after deleting folder, same thing happens. Is it worth trying to install manually?

**Comment by Lusamine** [comment] 2022-04-01 02:56
You can try zipping up the entire folder and uploading the zip here so I can take a look.

**Comment by intriguedperson** [comment] 2022-04-01 03:03
[trainers.zip](https://github.com/architdate/PKHeX-Plugins/files/8394376/trainers.zip)

**Comment by Lusamine** [comment] 2022-04-01 03:09
Works for me with fresh install. Have you tried moving to another folder?
![importtrainerdata](https://user-images.githubusercontent.com/30205550/161187581-ec39eaa2-155a-45d2-a85d-b893779e0fce.gif)

**Comment by intriguedperson** [comment] 2022-04-01 03:19
Ok, it works on a blank save but not on my save where the TID/SID came from. Is that expected? Is it an issue with my save?

**Comment by Lusamine** [comment] 2022-04-01 03:23
I'm using it on a save with the same TID/SID and it still works for me.

**Comment by intriguedperson** [comment] 2022-04-01 03:27
Okay I've tried some other saves I have and it doesn't work if I have any save loaded but it does work on a blank save. Any idea what to try next? Thanks for all your help

**Comment by intriguedperson** [comment] 2022-04-04 00:53
I've figured out if I open a save file > open using pkhex, when I try to import a set using alm it doesn't read the trainer folder data. However, if I open pkhex first, then open > select the same save. It works and uses trainer data correctly. Is this an issue with my windows or pkhex/ALM?

**Comment by intriguedperson** [comment] 2022-04-04 22:26
No idea what application.startuppath and whatnot means, but it sounds like you guys know whats wrong. Let me know if I can do anything to help if its not reproducable. Thanks!

**Closed** 2022-05-10 05:06 UTC
Labels: bug
